import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Afroza',
      email: 'admin@demo.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
    },
    {
      name: 'Mono',
      email: 'user@demo.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Adidas Sports Bag',
      slug: 'adidas-sports-bag',
      category: 'Bags',
      image: '/images/p1.jpg',
      price: 90,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4,
      numReviews: 9,
      description: 'High quality and convenient sports bag',
    },
    {
      // _id: '2',
      name: 'Matador Ball Pen',
      slug: 'matador-ball-pen',
      category: 'pen',
      image: '/images/p2.jpg',
      price: 4,
      countInStock: 4,
      brand: 'Matador',
      rating: 4.5,
      numReviews: 18,
      description: 'Black Ball Pen',
    },
    {
      //_id: '3',
      name: 'Matador 2B Pencil',
      slug: 'matador-2b-pencil',
      category: 'pencil',
      image: '/images/p3.jpg',
      price: 3,
      countInStock: 100,
      brand: 'Matador',
      rating: 4.5,
      numReviews: 8,
      description: 'Black color pencil',
    },
    {
      //  _id: '4',
      name: 'White Spiral Notebook',
      slug: 'white-notebook',
      category: 'notebook',
      image: '/images/p4.jpg',
      price: 5,
      countInStock: 100,
      brand: 'Matador',
      rating: 4.8,
      numReviews: 12,
      description: 'spiral binded white notebook',
    },
  ],
};
export default data;
